### ISSUE TITLE
Add "senza wait" command

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#141] opened 2015-11-12 15:50 UTC
We need a command to wait for successful CF stack creation or deletion, i.e. exactly what @sarnowski implemented here: https://github.com/zalando/stups2go/blob/master/agent/tools/wait-for-stack

```bash
$ senza wait senza.yaml 1

**Comment by hjacobs** [comment] 2015-11-13 13:27
@jmcs also said: "I'm also trying to the wait command since it would greatly simplify the script I'm doing right now"

**Comment by elgalu** [comment] 2015-11-18 10:34
Ha! I was about to open this same issue :) `senza wait senza.yaml 30m`

**Comment by hjacobs** [comment] 2015-11-18 11:11
The "wait" command is now available in https://github.com/zalando-stups/senza/releases/tag/1.0.16

**Comment by elgalu** [comment] 2015-11-18 11:47
It gets stuck if the same application version was deleted before:

```sh
$ senza wait pacts staging --timeout 7200
Waiting up to 7199 more secs for stacks pacts-staging (CREATE_IN_PROGRESS), pacts-staging (DELETE_COMPLETE)..
...{{same}}...
Waiting up to 6935 more secs for stacks pacts-staging (CREATE_IN_PROGRESS), pacts-staging (DELETE_COMPLETE)..
Waiting up to 6930 more secs for stack pacts-staging (DELETE_COMPLETE)..
...{{same}}...
Waiting up to 6924 more secs for stack pacts-staging (DELETE_COMPLETE)..
...{{stuck here}}...
```

This will help debug it:
```sh
$ senza list pacts staging --all
Stack Name│Ver.   │Status         │Created│Description                             
pacts      staging CREATE_COMPLETE  9m ago Pacts (ImgTag: 0.1.3, TargetDB: staging) 
pacts      staging DELETE_COMPLETE  1h ago Pacts (ImgTag: 0.1.3, TargetDB: staging) 
pacts      staging DELETE_COMPLETE 12d ago Pacts (TargetDB: staging, ImgTag: 0.1.2) 
pacts      staging DELETE_COMPLETE 13d ago Pacts (TargetDB: staging, ImgTag: 0.0.9) 
pacts      staging DELETE_COMPLETE 13d ago Pacts (TargetDB: staging, ImgTag: 0.0.8)
```

**Comment by hjacobs** [comment] 2015-11-18 11:52
@elgalu True, re-using the same stack version is not supported right now --- we need to fix this

**Comment by elgalu** [comment] 2015-11-18 18:45
Another thing that might bite us are expired credentials during the wait, perhaps we should automatically `mai` upon expired credentials?

```sh
Waiting up to 3846 more secs for stack pacts-staging (DELETE_COMPLETE)..
Waiting up to 3841 more secs for stack pacts-staging (DELETE_COMPLETE)..
AWS credentials have expired. Use the "mai" command line tool to get a new temporary access key.
```

**Comment by hjacobs** [comment] 2015-11-18 18:51
@elgalu we already had the discussion about calling "mai" --- I'm against it because it would mean wrapping any API with "try / except" and re-trying after successful "mai". None of the tools (including Senza) which use AWS SDKs should invoke "mai" as AWS credentials might really come from "anywhere" (e.g. transparently via IAM on EC2 instances).

**Comment by hjacobs** [comment] 2015-11-18 18:52
@elgalu you can always leave "mai" running with the "--refresh" option.

**Comment by elgalu** [comment] 2015-11-18 18:53
Ah `mai --refresh` is enough for me :)

**Comment by hjacobs** [comment] 2015-11-23 19:16
Added status reasons to ease troubleshooting in https://github.com/zalando-stups/senza/releases/tag/1.0.22

**Comment by chutium** [comment] 2015-11-24 11:25
oops, this issue is closed? we got same problem by re-using same application version, will you open a new issue for this?

i believe the status "DELETE_COMPLETE" is only needed by when "deletion" is true, so maybe
```for stack in get_stacks(stack_refs, region, all=True):```
can be changed to
```for stack in get_stacks(stack_refs, region, all=deletion):```
but if deletion is true, the problem is still there... :D

**Comment by hjacobs** [comment] 2015-11-24 11:26
@chutium true, re-using stack versions needs to be fixed

**Comment by elgalu** [comment] 2015-11-27 09:36
1. Should be close this one as fixed and open a new issue to trace "senza wait support for re-using stack versions" ?

2. Could we have some kind of `senza traffic wait` option that waits for the DNS to be updated so that we know when we can delete the stacks that truly have 0% traffic in order to free up resources?
e.g. I want to know when is safe to delete myapp-v1

```
senza traffic myapp v2 100
Calculating new weights.. OK
StackName│Version│Identif.│OldWeight%│Delta │Compensation│NewWeight%│Current
myapp    v1     myapp-v1 100.0      -100.0                0.0  
myapp    v2     myapp-v2   0.0       100.0              100.0 <
Setting weights for myapp.example.org... OK
```

**Comment by hjacobs** [comment] 2015-11-27 12:15
@elgalu regarding DNS wait: there is no way of knowing if DNS switched for all clients, but you an use "senza status" to see how your own DNS resolves

**Comment by drummerwolli** [comment] 2016-02-09 18:16
any work/thought on this? i just stumbled upon this problem again ...

**Closed** 2016-04-13 09:32 UTC
Labels: enhancement
