### ISSUE TITLE
"senza traffic" error when one of the stack versions is being removed

### ISSUE THREAD

**Issue by v-stepanov** [zalando-stups/senza#364] opened 2016-09-26 12:16 UTC
We had three stacks of nakadi-sandbox (48, 52, 53), one of them was in the process of deletion (52). 
During that time I tried to switch 100% of traffic from one version to another (48 -> 53)
I got senza error 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/senza/error_handling.py", line 71, in __call__
    self.function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/senza/cli.py", line 1254, in traffic
    print_version_traffic(ref, region)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/senza/traffic.py", line 293, in print_version_traffic
    versions = list(get_stack_versions(stack_ref.name, region))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/senza/traffic.py", line 256, in get_stack_versions
    lbs = elb.describe_load_balancers(LoadBalancerNames=[res.physical_resource_id])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (LoadBalancerNotFound) when calling the DescribeLoadBalancers operation: Cannot find Load Balancer nakadi-sandbox-52
```

When the stack was completely removed I checked the current traffic distribution. Both 48 and 53 had 100% of traffic. After I repeated the command to switch traffic everything was fixed (stack 48 has 0%)

**Comment by jmcs** [comment] 2016-09-29 06:37
Duplicate of #312.

**Closed by jmcs** 2016-09-29 06:37 UTC
Labels: bug, duplicate
