### ISSUE TITLE
AWS seems to spawn new instances when trying to create a new stack with an existing version

### ISSUE THREAD

**Issue by ChristianLohmann** [zalando-stups/senza#3] opened 2015-04-13 12:24 UTC
If there are at least 2 versions of a stack available and one tries to deploy the uppermost version again AWS respawns new instances of the lower version according to the stack definition.
To reproduce there must be running instances of the uppermost version available and no active (terminated) instances of the lower one. Maybe reproducible in any other constellation.
I didn't try it with more than 2 stack versions so i don't know if it's an issue with just 2 of them.

**Comment by hjacobs** [comment] 2015-06-25 18:09
@ChristianLohmann I can't reproduce this behavior as you can't deploy an existing stack version twice (Cloud Formation will complain) --- I would close this issue if nobody else reports otherwise

**Comment by hjacobs** [comment] 2015-08-11 20:02
Closing this issue as no more reports came in :-)

**Closed by hjacobs** 2015-08-11 20:02 UTC
